package com.zx.wfm.bean;

import android.os.Parcel;

import com.avos.avoscloud.AVClassName;
import com.zx.wfm.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.zx.wfm.dao.MoviebeanDao;
import com.zx.wfm.dao.TelevisionbeanDao;

import java.util.Arrays;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MOVIEBEAN".
 */
@AVClassName("Moviebean")
public class Moviebean extends com.zx.wfm.bean.Basebean  implements java.io.Serializable {

    private String objectId;
    private String movieId;
    private String itemUrl;
    private String desc;
    private String videoName;
    private String videoHeadUrl;
    private Long time;
    private String movieDetail;
    private String TelevisionId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MoviebeanDao myDao;

    private Televisionbean televisionbean;
    private String televisionbean__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Moviebean() {
    }

    public Moviebean(String movieId) {
        this.movieId = movieId;
    }

    public Moviebean(String objectId, String movieId, String itemUrl, String desc, String videoName, String videoHeadUrl, Long time, String movieDetail, String TelevisionId) {
        this.objectId = objectId;
        this.movieId = movieId;
        this.itemUrl = itemUrl;
        this.desc = desc;
        this.videoName = videoName;
        this.videoHeadUrl = videoHeadUrl;
        this.time = time;
        this.movieDetail = movieDetail;
        this.TelevisionId = TelevisionId;
    }



    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMoviebeanDao() : null;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getMovieId() {
        return movieId;
    }

    public void setMovieId(String movieId) {
        this.movieId = movieId;
    }

    public String getItemUrl() {
        return itemUrl;
    }

    public void setItemUrl(String itemUrl) {
        this.itemUrl = itemUrl;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getVideoName() {
        return videoName;
    }

    public void setVideoName(String videoName) {
        this.videoName = videoName;
    }

    public String getVideoHeadUrl() {
        return videoHeadUrl;
    }

    public void setVideoHeadUrl(String videoHeadUrl) {
        this.videoHeadUrl = videoHeadUrl;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getMovieDetail() {
        return movieDetail;
    }

    public void setMovieDetail(String movieDetail) {
        this.movieDetail = movieDetail;
    }

    public String getTelevisionId() {
        return TelevisionId;
    }

    public void setTelevisionId(String TelevisionId) {
        this.TelevisionId = TelevisionId;
    }

    /** To-one relationship, resolved on first access. */
    public Televisionbean getTelevisionbean() {
        String __key = this.TelevisionId;
        if (televisionbean__resolvedKey == null || televisionbean__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TelevisionbeanDao targetDao = daoSession.getTelevisionbeanDao();
            Televisionbean televisionbeanNew = targetDao.load(__key);
            synchronized (this) {
                televisionbean = televisionbeanNew;
            	televisionbean__resolvedKey = __key;
            }
        }
        return televisionbean;
    }

    public void setTelevisionbean(Televisionbean televisionbean) {
        synchronized (this) {
            this.televisionbean = televisionbean;
            TelevisionId = televisionbean == null ? null : televisionbean.getTelevisionId();
            televisionbean__resolvedKey = TelevisionId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }


    // KEEP METHODS - put your custom methods here
//此处为我们的默认实现，当然你也可以自行实现
    public static final Creator CREATOR = new Creator<Moviebean>() {
        @Override
        public Moviebean createFromParcel(Parcel source) {
            return new Moviebean(source);
        }

        @Override
        public Moviebean[] newArray(int size) {
            return new Moviebean[0];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    public Moviebean(Parcel source) {
       objectId=source.readString();
        movieId=source.readString();
        itemUrl=source.readString();
        desc=source.readString();
        videoName=source.readString();
        videoHeadUrl=source.readString();
        time=source.readLong();
        movieDetail=source.readString();
        TelevisionId=source.readString();
    }

    @Override
    public void writeToParcel(Parcel out, int i) {
        out.writeString( objectId);
        out.writeString( movieId);
        out.writeString(itemUrl);
        out.writeString( desc);
        out.writeString( videoName);
        out.writeString( videoHeadUrl);
        out.writeLong(System.currentTimeMillis());
        out.writeString( movieDetail);
        out.writeString( TelevisionId);
    }

    @Override
    public String toString() {
        return "Moviebean{" +
                "objectId='" + objectId + '\'' +
                ", movieId='" + movieId + '\'' +
                ", itemUrl='" + itemUrl + '\'' +
                ", desc='" + desc + '\'' +
                ", videoName='" + videoName + '\'' +
                ", videoHeadUrl='" + videoHeadUrl + '\'' +
                ", time=" + time +
                ", movieDetail='" + movieDetail + '\'' +
                ", TelevisionId='" + TelevisionId + '\'' +
                ", daoSession=" + daoSession +
                ", myDao=" + myDao +
                ", televisionbean=" + televisionbean +
                ", televisionbean__resolvedKey='" + televisionbean__resolvedKey + '\'' +
                '}';
    }

    @Override
    protected List<String> getField() {
        return Arrays.asList("objectId","movieId","itemUrl","videoName","videoHeadUrl","movieDetail","TelevisionId","desc","time");
    }
    // KEEP METHODS END

}
