package com.zx.wfm.bean;

import com.zx.wfm.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.zx.wfm.dao.BaseUserDao;
import com.zx.wfm.dao.MovieCourseDao;
import com.zx.wfm.dao.TelevisionbeanDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MOVIE_COURSE".
 */
public class MovieCourse extends com.zx.wfm.bean.Basebean  implements java.io.Serializable {

    private Long time;
    private String uid;
    private String TelevisionId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MovieCourseDao myDao;

    private BaseUser baseUser;
    private String baseUser__resolvedKey;

    private Televisionbean televisionbean;
    private String televisionbean__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MovieCourse() {
    }

    public MovieCourse(Long time, String uid, String TelevisionId) {
        this.time = time;
        this.uid = uid;
        this.TelevisionId = TelevisionId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMovieCourseDao() : null;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getTelevisionId() {
        return TelevisionId;
    }

    public void setTelevisionId(String TelevisionId) {
        this.TelevisionId = TelevisionId;
    }

    /** To-one relationship, resolved on first access. */
    public BaseUser getBaseUser() {
        String __key = this.uid;
        if (baseUser__resolvedKey == null || baseUser__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BaseUserDao targetDao = daoSession.getBaseUserDao();
            BaseUser baseUserNew = targetDao.load(__key);
            synchronized (this) {
                baseUser = baseUserNew;
            	baseUser__resolvedKey = __key;
            }
        }
        return baseUser;
    }

    public void setBaseUser(BaseUser baseUser) {
        synchronized (this) {
            this.baseUser = baseUser;
            uid = baseUser == null ? null : baseUser.getUid();
            baseUser__resolvedKey = uid;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Televisionbean getTelevisionbean() {
        String __key = this.TelevisionId;
        if (televisionbean__resolvedKey == null || televisionbean__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TelevisionbeanDao targetDao = daoSession.getTelevisionbeanDao();
            Televisionbean televisionbeanNew = targetDao.load(__key);
            synchronized (this) {
                televisionbean = televisionbeanNew;
            	televisionbean__resolvedKey = __key;
            }
        }
        return televisionbean;
    }

    public void setTelevisionbean(Televisionbean televisionbean) {
        synchronized (this) {
            this.televisionbean = televisionbean;
            TelevisionId = televisionbean == null ? null : televisionbean.getTelevisionId();
            televisionbean__resolvedKey = TelevisionId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
