package com.zx.wfm.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.text.TextUtils;

import com.avos.avoscloud.AVClassName;

import java.util.Arrays;
import java.util.List;

/**
 * Entity mapped to table "TELE_MSGBEAN".
 */
@AVClassName("TeleMsgbean")
public class TeleMsgbean extends com.zx.wfm.bean.Basebean  implements java.io.Serializable {

    private String objectId;
    private String TelevisionId;
    private String userid;
    private String playNum;
    private String total;
    private String isZan;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TeleMsgbean() {
    }

    public TeleMsgbean(String TelevisionId) {
        this.TelevisionId = TelevisionId;
    }

    public TeleMsgbean(String objectId, String TelevisionId, String userid, String playNum, String total, String isZan) {
        this.objectId = objectId;
        this.TelevisionId = TelevisionId;
        this.userid = userid;
        this.playNum = playNum;
        this.total = total;
        this.isZan = isZan;
    }

    public String getTelevisionId() {
        return TelevisionId;
    }

    public void setTelevisionId(String TelevisionId) {
        this.TelevisionId = TelevisionId;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getPlayNum() {
        return playNum;
    }

    public void setPlayNum(String playNum) {
        this.playNum = playNum;
    }

    public String getTotal() {
        return total;
    }

    public void setTotal(String total) {
        this.total = total;
    }

    public String getIsZan() {
        return isZan;
    }

    public void setIsZan(String isZan) {
        this.isZan = isZan;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    protected List<String> getField() {
        return Arrays.asList("objectId","TelevisionId","userid","playNum","total","isZan");
    }
    @Override
    public void writeToParcel(Parcel out, int i) {
        out.writeString(objectId);
        out.writeString(TelevisionId);
        out.writeString(userid);
        out.writeString(playNum);
        out.writeString(total);
        out.writeString(isZan);
    }
    private TeleMsgbean(Parcel in)
    {
        objectId = in.readString();
        TelevisionId=in.readString();
        userid=in.readString();
        playNum=in.readString();
        total=in.readString();
        isZan=in.readString();
    }

    public static final Creator CREATOR = new Creator<TeleMsgbean>() {
        @Override
        public TeleMsgbean createFromParcel(Parcel source) {
            return new TeleMsgbean(source);
        }

        @Override
        public TeleMsgbean[] newArray(int size) {
            return new TeleMsgbean[0];
        }
    };

    public void setObjectId(String objectId) {
        this.objectId=objectId;
        super.setObjectId(objectId);
    }

    public String getObjectId() {
        if(!TextUtils.isEmpty(objectId)){
            return objectId;
        }
        return super.getObjectId();
    }

    @Override
    public boolean equals(Object obj) {
        String self=get("TelevisionId")+"";
        Televisionbean bean= (Televisionbean) obj;
        if(bean==null){
            return  false;
        }
        if(!TextUtils.isEmpty(self)){
            return self.equals(bean.get("TelevisionId"))||self.equals(bean.getTelevisionId());
        }else if(!TextUtils.isEmpty(getTelevisionId())){
            return getTelevisionId().equals(bean.getTelevisionId())||getTelevisionId().equals(bean.get("TelevisionId"));
        }
        return false;
    }
    // KEEP METHODS END

}
