package com.zx.wfm.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zx.wfm.bean.test;

import com.zx.wfm.dao.testDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testDaoConfig;

    private final testDao testDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testDaoConfig = daoConfigMap.get(testDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        testDao = new testDao(testDaoConfig, this);

        registerDao(test.class, testDao);
    }
    
    public void clear() {
        testDaoConfig.getIdentityScope().clear();
    }

    public testDao getTestDao() {
        return testDao;
    }

}
