package com.zx.wfm.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zx.wfm.bean.BaseUser;
import com.zx.wfm.bean.IDCard;
import com.zx.wfm.bean.Televisionbean;
import com.zx.wfm.bean.Moviebean;
import com.zx.wfm.bean.MovieCourse;

import com.zx.wfm.dao.BaseUserDao;
import com.zx.wfm.dao.IDCardDao;
import com.zx.wfm.dao.TelevisionbeanDao;
import com.zx.wfm.dao.MoviebeanDao;
import com.zx.wfm.dao.MovieCourseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baseUserDaoConfig;
    private final DaoConfig iDCardDaoConfig;
    private final DaoConfig televisionbeanDaoConfig;
    private final DaoConfig moviebeanDaoConfig;
    private final DaoConfig movieCourseDaoConfig;

    private final BaseUserDao baseUserDao;
    private final IDCardDao iDCardDao;
    private final TelevisionbeanDao televisionbeanDao;
    private final MoviebeanDao moviebeanDao;
    private final MovieCourseDao movieCourseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baseUserDaoConfig = daoConfigMap.get(BaseUserDao.class).clone();
        baseUserDaoConfig.initIdentityScope(type);

        iDCardDaoConfig = daoConfigMap.get(IDCardDao.class).clone();
        iDCardDaoConfig.initIdentityScope(type);

        televisionbeanDaoConfig = daoConfigMap.get(TelevisionbeanDao.class).clone();
        televisionbeanDaoConfig.initIdentityScope(type);

        moviebeanDaoConfig = daoConfigMap.get(MoviebeanDao.class).clone();
        moviebeanDaoConfig.initIdentityScope(type);

        movieCourseDaoConfig = daoConfigMap.get(MovieCourseDao.class).clone();
        movieCourseDaoConfig.initIdentityScope(type);

        baseUserDao = new BaseUserDao(baseUserDaoConfig, this);
        iDCardDao = new IDCardDao(iDCardDaoConfig, this);
        televisionbeanDao = new TelevisionbeanDao(televisionbeanDaoConfig, this);
        moviebeanDao = new MoviebeanDao(moviebeanDaoConfig, this);
        movieCourseDao = new MovieCourseDao(movieCourseDaoConfig, this);

        registerDao(BaseUser.class, baseUserDao);
        registerDao(IDCard.class, iDCardDao);
        registerDao(Televisionbean.class, televisionbeanDao);
        registerDao(Moviebean.class, moviebeanDao);
        registerDao(MovieCourse.class, movieCourseDao);
    }
    
    public void clear() {
        baseUserDaoConfig.getIdentityScope().clear();
        iDCardDaoConfig.getIdentityScope().clear();
        televisionbeanDaoConfig.getIdentityScope().clear();
        moviebeanDaoConfig.getIdentityScope().clear();
        movieCourseDaoConfig.getIdentityScope().clear();
    }

    public BaseUserDao getBaseUserDao() {
        return baseUserDao;
    }

    public IDCardDao getIDCardDao() {
        return iDCardDao;
    }

    public TelevisionbeanDao getTelevisionbeanDao() {
        return televisionbeanDao;
    }

    public MoviebeanDao getMoviebeanDao() {
        return moviebeanDao;
    }

    public MovieCourseDao getMovieCourseDao() {
        return movieCourseDao;
    }

}
