package com.zx.wfm.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.zx.wfm.bean.BaseUser;

import com.zx.wfm.bean.IDCard;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IDCARD".
*/
public class IDCardDao extends AbstractDao<IDCard, Long> {

    public static final String TABLENAME = "IDCARD";

    /**
     * Properties of entity IDCard.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property CardId = new Property(0, Long.class, "cardId", true, "CARD_ID");
        public final static Property Validity = new Property(1, Long.class, "validity", false, "VALIDITY");
        public final static Property Uid = new Property(2, String.class, "uid", false, "UID");
    };

    private DaoSession daoSession;


    public IDCardDao(DaoConfig config) {
        super(config);
    }
    
    public IDCardDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IDCARD\" (" + //
                "\"CARD_ID\" INTEGER PRIMARY KEY ," + // 0: cardId
                "\"VALIDITY\" INTEGER," + // 1: validity
                "\"UID\" TEXT);"); // 2: uid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IDCARD\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, IDCard entity) {
        stmt.clearBindings();
 
        Long cardId = entity.getCardId();
        if (cardId != null) {
            stmt.bindLong(1, cardId);
        }
 
        Long validity = entity.getValidity();
        if (validity != null) {
            stmt.bindLong(2, validity);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(3, uid);
        }
    }

    @Override
    protected void attachEntity(IDCard entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public IDCard readEntity(Cursor cursor, int offset) {
        IDCard entity = new IDCard( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // cardId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // validity
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // uid
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, IDCard entity, int offset) {
        entity.setCardId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setValidity(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setUid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(IDCard entity, long rowId) {
        entity.setCardId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(IDCard entity) {
        if(entity != null) {
            return entity.getCardId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBaseUserDao().getAllColumns());
            builder.append(" FROM IDCARD T");
            builder.append(" LEFT JOIN BASE_USER T0 ON T.\"UID\"=T0.\"UID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected IDCard loadCurrentDeep(Cursor cursor, boolean lock) {
        IDCard entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BaseUser baseUser = loadCurrentOther(daoSession.getBaseUserDao(), cursor, offset);
        entity.setBaseUser(baseUser);

        return entity;    
    }

    public IDCard loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<IDCard> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<IDCard> list = new ArrayList<IDCard>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<IDCard> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<IDCard> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
