package com.zx.wfm.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.zx.wfm.bean.BaseUser;
import com.zx.wfm.bean.Televisionbean;

import com.zx.wfm.bean.MovieCourse;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOVIE_COURSE".
*/
public class MovieCourseDao extends AbstractDao<MovieCourse, Void> {

    public static final String TABLENAME = "MOVIE_COURSE";

    /**
     * Properties of entity MovieCourse.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ObjectId = new Property(0, String.class, "objectId", false, "OBJECT_ID");
        public final static Property Time = new Property(1, Long.class, "time", false, "TIME");
        public final static Property Uid = new Property(2, String.class, "uid", false, "UID");
        public final static Property TelevisionId = new Property(3, String.class, "TelevisionId", false, "TELEVISION_ID");
    };

    private DaoSession daoSession;

    private Query<MovieCourse> baseUser_MovieCourseListQuery;
    private Query<MovieCourse> televisionbean_MovieCourseListQuery;

    public MovieCourseDao(DaoConfig config) {
        super(config);
    }
    
    public MovieCourseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOVIE_COURSE\" (" + //
                "\"OBJECT_ID\" TEXT," + // 0: objectId
                "\"TIME\" INTEGER," + // 1: time
                "\"UID\" TEXT," + // 2: uid
                "\"TELEVISION_ID\" TEXT);"); // 3: TelevisionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOVIE_COURSE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MovieCourse entity) {
        stmt.clearBindings();
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(1, objectId);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(2, time);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(3, uid);
        }
 
        String TelevisionId = entity.getTelevisionId();
        if (TelevisionId != null) {
            stmt.bindString(4, TelevisionId);
        }
    }

    @Override
    protected void attachEntity(MovieCourse entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public MovieCourse readEntity(Cursor cursor, int offset) {
        MovieCourse entity = new MovieCourse( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // objectId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // time
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // uid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // TelevisionId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MovieCourse entity, int offset) {
        entity.setObjectId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTime(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setUid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTelevisionId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(MovieCourse entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(MovieCourse entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "movieCourseList" to-many relationship of BaseUser. */
    public List<MovieCourse> _queryBaseUser_MovieCourseList(String uid) {
        synchronized (this) {
            if (baseUser_MovieCourseListQuery == null) {
                QueryBuilder<MovieCourse> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Uid.eq(null));
                baseUser_MovieCourseListQuery = queryBuilder.build();
            }
        }
        Query<MovieCourse> query = baseUser_MovieCourseListQuery.forCurrentThread();
        query.setParameter(0, uid);
        return query.list();
    }

    /** Internal query to resolve the "movieCourseList" to-many relationship of Televisionbean. */
    public List<MovieCourse> _queryTelevisionbean_MovieCourseList(String TelevisionId) {
        synchronized (this) {
            if (televisionbean_MovieCourseListQuery == null) {
                QueryBuilder<MovieCourse> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TelevisionId.eq(null));
                televisionbean_MovieCourseListQuery = queryBuilder.build();
            }
        }
        Query<MovieCourse> query = televisionbean_MovieCourseListQuery.forCurrentThread();
        query.setParameter(0, TelevisionId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBaseUserDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getTelevisionbeanDao().getAllColumns());
            builder.append(" FROM MOVIE_COURSE T");
            builder.append(" LEFT JOIN BASE_USER T0 ON T.\"UID\"=T0.\"UID\"");
            builder.append(" LEFT JOIN TELEVISIONBEAN T1 ON T.\"TELEVISION_ID\"=T1.\"TELEVISION_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MovieCourse loadCurrentDeep(Cursor cursor, boolean lock) {
        MovieCourse entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BaseUser baseUser = loadCurrentOther(daoSession.getBaseUserDao(), cursor, offset);
        entity.setBaseUser(baseUser);
        offset += daoSession.getBaseUserDao().getAllColumns().length;

        Televisionbean televisionbean = loadCurrentOther(daoSession.getTelevisionbeanDao(), cursor, offset);
        entity.setTelevisionbean(televisionbean);

        return entity;    
    }

    public MovieCourse loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MovieCourse> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MovieCourse> list = new ArrayList<MovieCourse>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MovieCourse> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MovieCourse> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
